anchor: rna10k
datasets:
- name: rna10k
  modality: rna
  counts: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/10k_rna/counts.mtx
  barcodes: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/10k_rna/barcodes.txt
  features: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/10k_rna/features.txt
  pca: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/10k_rna/pca_50.txt
- name: atac10k_ext
  modality: atac
  counts: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/atac10k_ext/counts.mtx
  barcodes: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/atac10k_ext/barcodes.txt
  features: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/atac10k_ext/features.txt
  pca: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/data/atac10k_ext/pca_50.txt
output_dir: /Volumes/samsung_ssd/tmp/pbmc-10k-unpaired-grn/results/integration_unpaired
s_shared_cells: 8161
M_samples: 2000
alpha: 0.75
S_iterations: 25
gw_epsilon: 1.0e-05
gw_reg: 0.001
